version: '3.1'

services:
  db:
    image: postgres:13.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mangahub

volumes:
  pgdata: